// flow-typed signature: 0bb59b2587f75b0f3d614f9260c9853f
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.18.9/flow_v0.185.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
