/* eslint-env mocha */
import expect from 'expect';
import AXObjectRoleMap from '../../src/AXObjectRoleMap';

describe('AXObjectRoleMap', function () {
  describe('content', function () {
    it('should have specific elements', function () {
      expect(AXObjectRoleMap.entries()).toEqual(
        expect.arrayContaining(
          [
            ["AlertDialogRole", [{"name": "alertdialog"}]],
            ["AlertRole", [{"name": "alert"}]],
            ["ApplicationRole", [{"name": "application"}]],
            ["ArticleRole", [{"name": "article"}]],
            ["BannerRole", [{"name": "banner"}]],
            ["BusyIndicatorRole", [{"attributes": [{"name": "aria-busy", "value": "true"}]}]],
            ["ButtonRole", [{"name": "button"}]],
            ["CellRole", [{"name": "cell"}, {"name": "gridcell"}]],
            ["CheckBoxRole", [{"name": "checkbox"}]],
            ["ColumnHeaderRole", [{"name": "columnheader"}]],
            ["ComboBoxRole", [{"name": "combobox"}]],
            ["ComplementaryRole", [{"name": "complementary"}]],
            ["ContentInfoRole", [{"name": "structureinfo"}]],
            ["DialogRole", [{"name": "dialog"}]],
            ["DirectoryRole", [{"name": "directory"}]],
            ["DocumentRole", [{"name": "document"}]],
            ["FeedRole", [{"name": "feed"}]],
            ["FigureRole", [{"name": "figure"}]],
            ["FormRole", [{"name": "form"}]],
            ["GridRole", [{"name": "grid"}]],
            ["GroupRole", [{"name": "group"}]],
            ["HeadingRole", [{"name": "heading"}]],
            ["ImageRole", [{"name": "img"}]],
            ["LinkRole", [{"name": "link"}]],
            ["ListBoxOptionRole", [{"name": "option"}]],
            ["ListBoxRole", [{"name": "listbox"}]],
            ["ListItemRole", [{"name": "listitem"}]],
            ["ListRole", [{"name": "list"}]],
            ["LogRole", [{"name": "log"}]],
            ["MainRole", [{"name": "main"}]],
            ["MarqueeRole", [{"name": "marquee"}]],
            ["MathRole", [{"name": "math"}]],
            ["MenuBarRole", [{"name": "menubar"}]],
            ["MenuItemRole", [{"name": "menuitem"}]],
            ["MenuItemCheckBoxRole", [{"name": "menuitemcheckbox"}]],
            ["MenuItemRadioRole", [{"name": "menuitemradio"}]],
            ["MenuRole", [{"name": "menu"}]],
            ["NavigationRole", [{"name": "navigation"}]],
            ["NoneRole", [{"name": "none"}]],
            ["NoteRole", [{"name": "note"}]],
            ["PresentationalRole", [{"name": "presentation"}]],
            ["ProgressIndicatorRole", [{"name": "progressbar"}]],
            ["RadioButtonRole", [{"name": "radio"}]],
            ["RadioGroupRole", [{"name": "radiogroup"}]],
            ["RegionRole", [{"name": "region"}]],
            ["RowHeaderRole", [{"name": "rowheader"}]],
            ["RowRole", [{"name": "row"}]],
            ["ScrollBarRole", [{"name": "scrollbar"}]],
            ["SearchRole", [{"name": "search"}]],
            ["SearchBoxRole", [{"name": "searchbox"}]],
            ["SliderRole", [{"name": "slider"}]],
            ["SpinButtonRole", [{"name": "spinbutton"}]],
            ["SplitterRole", [{"name": "separator"}]],
            ["StatusRole", [{"name": "status"}]],
            ["SwitchRole", [{"name": "switch"}]],
            ["TabGroupRole", [{"name": "tablist"}]],
            ["TabRole", [{"name": "tab"}]],
            ["TableRole", [{"name": "table"}]],
            ["TabListRole", [{"name": "tablist"}]],
            ["TabPanelRole", [{"name": "tabpanel"}]],
            ["TermRole", [{"name": "term"}]],
            ["TextFieldRole", [{"name": "textbox"}]],
            ["TimerRole", [{"name": "timer"}]],
            ["ToggleButtonRole", [{"attributes": [{"name": "aria-pressed"}]}]],
            ["ToolbarRole", [{"name": "toolbar"}]],
            ["TreeRole", [{"name": "tree"}]],
            ["TreeGridRole", [{"name": "treegrid"}]],
            ["TreeItemRole", [{"name": "treeitem"}]],
            ["UserInterfaceTooltipRole", [{"name": "tooltip"}]],
          ]
        )
      );
    });
  });
});
