/* eslint-env mocha */
import expect from 'expect';
import AXObjectsMap from '../../src/AXObjectsMap';

describe('AXObjectsMap', function () {
  it('should be a Map', function () {
    expect(AXObjectsMap instanceof Map).toBe(true);
  });
  describe('content', function () {
    it('should have specific entries', function () {
      expect(Array.from(AXObjectsMap.entries())).toEqual(
        expect.arrayContaining(
          [
            ["AbbrRole", expect.any(Object)],
            ["AlertDialogRole", expect.any(Object)],
            ["AlertRole", expect.any(Object)],
            ["AnnotationRole", expect.any(Object)],
            ["ApplicationRole", expect.any(Object)],
            ["ArticleRole", expect.any(Object)],
            ["AudioRole", expect.any(Object)],
            ["BannerRole", expect.any(Object)],
            ["BlockquoteRole", expect.any(Object)],
            ["BusyIndicatorRole", expect.any(Object)],
            ["ButtonRole", expect.any(Object)],
            ["CanvasRole", expect.any(Object)],
            ["CaptionRole", expect.any(Object)],
            ["CellRole", expect.any(Object)],
            ["CheckBoxRole", expect.any(Object)],
            ["ColorWellRole", expect.any(Object)],
            ["ColumnHeaderRole", expect.any(Object)],
            ["ColumnRole", expect.any(Object)],
            ["ComboBoxRole", expect.any(Object)],
            ["ComplementaryRole", expect.any(Object)],
            ["ContentInfoRole", expect.any(Object)],
            ["DateRole", expect.any(Object)],
            ["DateTimeRole", expect.any(Object)],
            ["DefinitionRole", expect.any(Object)],
            ["DescriptionListDetailRole", expect.any(Object)],
            ["DescriptionListRole", expect.any(Object)],
            ["DescriptionListTermRole", expect.any(Object)],
            ["DetailsRole", expect.any(Object)],
            ["DialogRole", expect.any(Object)],
            ["DirectoryRole", expect.any(Object)],
            ["DisclosureTriangleRole", expect.any(Object)],
            ["DivRole", expect.any(Object)],
            ["DocumentRole", expect.any(Object)],
            ["EmbeddedObjectRole", expect.any(Object)],
            ["FeedRole", expect.any(Object)],
            ["FigcaptionRole", expect.any(Object)],
            ["FigureRole", expect.any(Object)],
            ["FooterRole", expect.any(Object)],
            ["FormRole", expect.any(Object)],
            ["GridRole", expect.any(Object)],
            ["GroupRole", expect.any(Object)],
            ["HeadingRole", expect.any(Object)],
            ["IframePresentationalRole", expect.any(Object)],
            ["IframeRole", expect.any(Object)],
            ["IgnoredRole", expect.any(Object)],
            ["ImageMapLinkRole", expect.any(Object)],
            ["ImageMapRole", expect.any(Object)],
            ["ImageRole", expect.any(Object)],
            ["InlineTextBoxRole", expect.any(Object)],
            ["InputTimeRole", expect.any(Object)],
            ["LabelRole", expect.any(Object)],
            ["LegendRole", expect.any(Object)],
            ["LineBreakRole", expect.any(Object)],
            ["LinkRole", expect.any(Object)],
            ["ListBoxOptionRole", expect.any(Object)],
            ["ListBoxRole", expect.any(Object)],
            ["ListItemRole", expect.any(Object)],
            ["ListMarkerRole", expect.any(Object)],
            ["ListRole", expect.any(Object)],
            ["LogRole", expect.any(Object)],
            ["MainRole", expect.any(Object)],
            ["MarkRole", expect.any(Object)],
            ["MarqueeRole", expect.any(Object)],
            ["MathRole", expect.any(Object)],
            ["MenuBarRole", expect.any(Object)],
            ["MenuButtonRole", expect.any(Object)],
            ["MenuItemRole", expect.any(Object)],
            ["MenuItemCheckBoxRole", expect.any(Object)],
            ["MenuItemRadioRole", expect.any(Object)],
            ["MenuListOptionRole", expect.any(Object)],
            ["MenuListPopupRole", expect.any(Object)],
            ["MenuRole", expect.any(Object)],
            ["MeterRole", expect.any(Object)],
            ["NavigationRole", expect.any(Object)],
            ["NoneRole", expect.any(Object)],
            ["NoteRole", expect.any(Object)],
            ["OutlineRole", expect.any(Object)],
            ["ParagraphRole", expect.any(Object)],
            ["PopUpButtonRole", expect.any(Object)],
            ["PreRole", expect.any(Object)],
            ["PresentationalRole", expect.any(Object)],
            ["ProgressIndicatorRole", expect.any(Object)],
            ["RadioButtonRole", expect.any(Object)],
            ["RadioGroupRole", expect.any(Object)],
            ["RegionRole", expect.any(Object)],
            ["RootWebAreaRole", expect.any(Object)],
            ["RowHeaderRole", expect.any(Object)],
            ["RowRole", expect.any(Object)],
            ["RubyRole", expect.any(Object)],
            ["RulerRole", expect.any(Object)],
            ["ScrollAreaRole", expect.any(Object)],
            ["ScrollBarRole", expect.any(Object)],
            ["SeamlessWebAreaRole", expect.any(Object)],
            ["SearchRole", expect.any(Object)],
            ["SearchBoxRole", expect.any(Object)],
            ["SliderRole", expect.any(Object)],
            ["SliderThumbRole", expect.any(Object)],
            ["SpinButtonRole", expect.any(Object)],
            ["SpinButtonPartRole", expect.any(Object)],
            ["SplitterRole", expect.any(Object)],
            ["StaticTextRole", expect.any(Object)],
            ["StatusRole", expect.any(Object)],
            ["SVGRootRole", expect.any(Object)],
            ["SwitchRole", expect.any(Object)],
            ["TabGroupRole", expect.any(Object)],
            ["TabRole", expect.any(Object)],
            ["TableHeaderContainerRole", expect.any(Object)],
            ["TableRole", expect.any(Object)],
            ["TabListRole", expect.any(Object)],
            ["TabPanelRole", expect.any(Object)],
            ["TermRole", expect.any(Object)],
            ["TextFieldRole", expect.any(Object)],
            ["TimeRole", expect.any(Object)],
            ["TimerRole", expect.any(Object)],
            ["ToggleButtonRole", expect.any(Object)],
            ["ToolbarRole", expect.any(Object)],
            ["TreeRole", expect.any(Object)],
            ["TreeGridRole", expect.any(Object)],
            ["TreeItemRole", expect.any(Object)],
            ["UserInterfaceTooltipRole", expect.any(Object)],
            ["VideoRole", expect.any(Object)],
            ["WebAreaRole", expect.any(Object)],
            ["WindowRole", expect.any(Object)]
          ]
        )
      );
    });
  });
});
