name: CI
on:
  push:
    branches:
      - main
      - "!dependabot/**"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 0.4'
      type: majors
      command: npm run tests-only

  flow:
    name: Flow type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        with:
          use-npm-ci: true
      - name: Flow type check
        run: npm run flow

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        with:
          use-npm-ci: true
      - name: Run ESLint
        run: npm run lint

  diff-breakUpAriaJSON:
    name: Compare JSON to src output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        with:
          use-npm-ci: true
      - name: Run diff check for the breakUpAriaJSON script
        run: node scripts/buildModelModules.js && git diff --exit-code -- src
